# Generated by Django 5.1.15 on 2026-06-20 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('customers', '0001_initial'),
        ('erp', '0002_initial'),
        ('trade_accounts', '0002_trade_credit_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='crm_opportunity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_draft', to='crm.crmopportunity'),
        ),
        migrations.AddField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='quote',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='erp.party'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='trade_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='trade_accounts.tradeaccount'),
        ),
        migrations.AlterField(
            model_name='tradecreditauditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
