# Generated by Django 5.1.15 on 2026-06-20 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_quote_workflow_fields'),
        ('trade_accounts', '0003_quote_crm_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='quote',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='converted_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quote', to='orders.order'),
        ),
        migrations.AddField(
            model_name='quote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='discount_cents',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='gst_total_cents',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quote',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='subtotal_ex_gst_cents',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='terms_and_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='discount_cents',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='gst_rate',
            field=models.DecimalField(decimal_places=4, default='0.1000', max_digits=5),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='line_gst_cents',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='line_subtotal_ex_gst_cents',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('converted', 'Converted'), ('declined', 'Declined')], db_index=True, default='draft', max_length=30),
        ),
        migrations.AlterModelTable(
            name='quote',
            table='trade_accounts_quote',
        ),
    ]
