# Generated by Django 5.1.15 on 2026-06-18 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('warehouse_type', models.CharField(choices=[('distribution', 'Distribution'), ('retail', 'Retail'), ('3pl', '3PL')], max_length=20)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('suburb', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=3)),
                ('postcode', models.CharField(blank=True, max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('allows_pickup', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'warehouses',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('receipt', 'Receipt'), ('sale', 'Sale'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('reservation', 'Reservation'), ('release', 'Release')], max_length=30)),
                ('quantity_change', models.IntegerField()),
                ('quantity_after', models.IntegerField()),
                ('reference_type', models.CharField(blank=True, max_length=30)),
                ('reference_id', models.BigIntegerField(blank=True, null=True)),
                ('unit_cost_cents', models.BigIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_transactions', to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('quantity_reserved', models.IntegerField(default=0)),
                ('reorder_point', models.IntegerField(default=0)),
                ('reorder_quantity', models.IntegerField(default=0)),
                ('last_counted_at', models.DateTimeField(blank=True, null=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_levels', to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_levels', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_levels',
                'unique_together': {('warehouse', 'variant')},
            },
        ),
    ]
