# Generated by Django 5.1.15 on 2026-06-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_warehouse_capacity_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.inventorylevel',),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.inventorytransaction',),
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['code']},
        ),
        migrations.AlterField(
            model_name='inventoryalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='movement_number',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('receipt', 'Stock In'), ('sale', 'Sale'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('reservation', 'Reservation'), ('release', 'Release')], max_length=30),
        ),
    ]
