/**
 * API configuration — single source of truth for base URL and route prefixes.
 * Aligns with Django REST Framework `/api/v1` namespace.
 */

/** Normalised base URL without trailing slash */
const rawBaseUrl =
  process.env.NEXT_PUBLIC_API_URL ?? "http://127.0.0.1:8000/api/v1";

/** Normalised base URL without trailing slash */
export const API_BASE_URL = rawBaseUrl.replace(/\/$/, "");

/** API version segment for future v2 expansion */
export const API_VERSION = "v1" as const;

/**
 * Canonical endpoint paths (relative to API_BASE_URL).
 * Add new ERP modules here — e.g. inventory, suppliers, finance.
 */
export const API_ENDPOINTS = {
  auth: {
    register: "/auth/register/",
    login: "/auth/login/",
    refresh: "/auth/refresh/",
    logout: "/auth/logout/",
    profile: "/auth/profile/",
    me: "/auth/me/",
    forgotPassword: "/auth/forgot-password/",
    resetPassword: "/auth/reset-password/",
    verifyEmail: "/auth/verify-email/",
    resendVerification: "/auth/resend-verification/",
    changePassword: "/auth/change-password/",
  },
  customers: {
    addresses: "/customers/addresses/",
    address: (addressId: string) => `/customers/addresses/${addressId}/`,
  },
  products: {
    list: "/products/",
    search: "/products/search/",
    compare: "/products/compare/",
    bySlug: (slug: string) => `/products/${slug}/`,
    byId: (id: string) => `/products/id/${id}/`,
    variant: (variantId: string) => `/products/variants/${variantId}/`,
  },
  categories: {
    list: "/categories/",
    bySlug: (slug: string) => `/categories/${slug}/`,
    products: (slug: string) => `/categories/${slug}/products/`,
  },
  brands: {
    list: "/brands/",
    bySlug: (slug: string) => `/brands/${slug}/`,
    products: (slug: string) => `/brands/${slug}/products/`,
  },
  cart: {
    root: "/cart/",
    items: "/cart/items/",
    item: (itemId: string) => `/cart/items/${itemId}/`,
    clear: "/cart/clear/",
    coupon: "/cart/coupon/",
    merge: "/cart/merge/",
  },
  wishlist: {
    root: "/wishlist/",
    items: "/wishlist/items/",
    item: (itemId: string) => `/wishlist/items/${itemId}/`,
  },
  orders: {
    list: "/orders/",
    create: "/orders/",
    byId: (orderId: string) => `/orders/${orderId}/`,
    cancel: (orderId: string) => `/orders/${orderId}/cancel/`,
    pack: (orderId: string) => `/orders/${orderId}/pack/`,
    ship: (orderId: string) => `/orders/${orderId}/ship/`,
    deliver: (orderId: string) => `/orders/${orderId}/deliver/`,
    refund: (orderId: string) => `/orders/${orderId}/refund/`,
    reorder: (orderId: string) => `/orders/${orderId}/reorder/`,
    invoice: (orderId: string) => `/orders/${orderId}/invoice/`,
  },
  payments: {
    config: "/payments/config/",
    webhook: "/payments/webhook/",
  },
  tradeAccounts: {
    me: "/trade-accounts/me/",
    apply: "/trade-accounts/apply/",
    quotes: "/trade-accounts/quotes/",
    quote: (quoteId: string) => `/trade-accounts/quotes/${quoteId}/`,
    adminApplications: "/trade-accounts/admin/applications/",
    adminApplicationReview: (id: string) =>
      `/trade-accounts/admin/applications/${id}/review/`,
    adminAccountCredit: (id: string) => `/trade-accounts/admin/accounts/${id}/credit/`,
  },
  admin: {
    dashboard: "/analytics/admin/dashboard/",
    customers: "/analytics/admin/customers/",
    customer: (id: string) => `/analytics/admin/customers/${id}/`,
    products: "/admin/products/",
    product: (id: string) => `/admin/products/${id}/`,
    productsLegacy: "/analytics/admin/products/",
    categories: "/admin/categories/",
    category: (id: string) => `/admin/categories/${id}/`,
    brands: "/admin/brands/",
    brand: (id: string) => `/admin/brands/${id}/`,
    reports: "/analytics/admin/reports/",
    reportsExport: "/analytics/admin/reports/export/",
    bi: {
      executive: "/analytics/admin/bi/executive/",
      sales: "/analytics/admin/bi/sales/",
      inventory: "/analytics/admin/bi/inventory/",
      procurement: "/analytics/admin/bi/procurement/",
      finance: "/analytics/admin/bi/finance/",
      hr: "/analytics/admin/bi/hr/",
      snapshot: "/analytics/admin/bi/snapshot/",
      kpis: "/analytics/admin/bi/kpis/",
      kpisEvaluate: "/analytics/admin/bi/kpis/evaluate/",
      kpi: (id: string) => `/analytics/admin/bi/kpis/${id}/`,
      reports: "/analytics/admin/bi/reports/",
      reportsExport: "/analytics/admin/bi/reports/export/",
      schedules: "/analytics/admin/bi/schedules/",
    },
  },
  suppliers: {
    list: "/suppliers/",
    admin: "/suppliers/admin/",
    adminDetail: (id: string) => `/suppliers/admin/${id}/`,
    purchaseOrders: "/suppliers/purchase-orders/",
    purchaseOrder: (id: string) => `/suppliers/purchase-orders/${id}/`,
    purchaseOrderSubmit: (id: string) => `/suppliers/purchase-orders/${id}/submit/`,
    purchaseOrderConfirm: (id: string) => `/suppliers/purchase-orders/${id}/confirm/`,
    purchaseOrderReceive: (id: string) => `/suppliers/purchase-orders/${id}/receive/`,
    purchaseOrderCancel: (id: string) => `/suppliers/purchase-orders/${id}/cancel/`,
  },
  inventory: {
    levels: "/inventory/levels/",
    level: (id: string) => `/inventory/levels/${id}/`,
    movements: "/inventory/movements/",
    movement: (id: string) => `/inventory/movements/${id}/`,
    transfers: "/inventory/transfers/",
    valuation: "/inventory/valuation/",
    ledgerSummary: "/inventory/ledger/summary/",
    lowStockAlerts: "/inventory/alerts/low-stock/",
    notifications: "/inventory/notifications/",
    notificationCount: "/inventory/notifications/unread-count/",
    acknowledgeNotification: (id: string) =>
      `/inventory/notifications/${id}/acknowledge/`,
    warehouses: "/inventory/warehouses/",
    adminWarehouses: "/inventory/admin/warehouses/",
    adminWarehouse: (id: string) => `/inventory/admin/warehouses/${id}/`,
    stockIn: "/inventory/stock-in/",
    stockOut: "/inventory/stock-out/",
    stockTransfer: "/inventory/stock-transfer/",
    adjustments: "/inventory/adjustments/",
  },
  crm: {
    dashboard: "/crm/admin/dashboard/",
    meta: "/crm/admin/meta/",
    leads: "/crm/admin/leads/",
    lead: (id: string) => `/crm/admin/leads/${id}/`,
    leadConvert: (id: string) => `/crm/admin/leads/${id}/convert/`,
    opportunities: "/crm/admin/opportunities/",
    opportunity: (id: string) => `/crm/admin/opportunities/${id}/`,
    activities: "/crm/admin/activities/",
    notes: "/crm/admin/notes/",
    timeline: "/crm/admin/timeline/",
    pipeline: "/crm/admin/pipeline/",
  },
  quotes: {
    dashboard: "/quotes/admin/dashboard/",
    list: "/quotes/admin/",
    detail: (id: string) => `/quotes/admin/${id}/`,
    lines: (id: string) => `/quotes/admin/${id}/lines/`,
    submit: (id: string) => `/quotes/admin/${id}/submit/`,
    approve: (id: string) => `/quotes/admin/${id}/approve/`,
    reject: (id: string) => `/quotes/admin/${id}/reject/`,
    send: (id: string) => `/quotes/admin/${id}/send/`,
    convert: (id: string) => `/quotes/admin/${id}/convert/`,
    pdf: (id: string) => `/quotes/admin/${id}/pdf/`,
    customerList: "/quotes/my/",
    customerDetail: (id: string) => `/quotes/my/${id}/`,
    customerAccept: (id: string) => `/quotes/my/${id}/accept/`,
    customerReject: (id: string) => `/quotes/my/${id}/reject/`,
    customerPdf: (id: string) => `/quotes/my/${id}/pdf/`,
  },
  procurement: {
    dashboard: "/procurement/admin/dashboard/",
    requests: "/procurement/admin/requests/",
    request: (id: string) => `/procurement/admin/requests/${id}/`,
    requestLines: (id: string) => `/procurement/admin/requests/${id}/lines/`,
    requestSubmit: (id: string) => `/procurement/admin/requests/${id}/submit/`,
    requestApprove: (id: string) => `/procurement/admin/requests/${id}/approve/`,
    requestReject: (id: string) => `/procurement/admin/requests/${id}/reject/`,
    requestConvert: (id: string) => `/procurement/admin/requests/${id}/convert/`,
    goodsReceipts: "/procurement/admin/goods-receipts/",
    supplierPerformance: (id: string) =>
      `/procurement/admin/suppliers/${id}/performance/`,
    poApprove: (id: string) => `/procurement/admin/purchase-orders/${id}/approve/`,
    portalDashboard: "/procurement/portal/dashboard/",
    portalPurchaseOrders: "/procurement/portal/purchase-orders/",
    portalPurchaseOrder: (id: string) => `/procurement/portal/purchase-orders/${id}/`,
    portalAcknowledge: (id: string) =>
      `/procurement/portal/purchase-orders/${id}/acknowledge/`,
    portalExpectedDelivery: (id: string) =>
      `/procurement/portal/purchase-orders/${id}/expected-delivery/`,
    portalPaymentStatus: (id: string) =>
      `/procurement/portal/purchase-orders/${id}/payment-status/`,
    portalDocuments: "/procurement/portal/documents/",
    portalDocumentUpload: "/procurement/portal/documents/upload/",
  },
  wms: {
    dashboard: "/wms/admin/dashboard/",
    bins: "/wms/admin/bins/",
    binInventory: "/wms/admin/bin-inventory/",
    transfers: "/wms/admin/transfers/",
    transfer: (id: string) => `/wms/admin/transfers/${id}/`,
    picks: "/wms/admin/picks/",
    pick: (id: string) => `/wms/admin/picks/${id}/`,
    pickStart: (id: string) => `/wms/admin/picks/${id}/start/`,
    pickRecord: (id: string) => `/wms/admin/picks/${id}/record/`,
    pickComplete: (id: string) => `/wms/admin/picks/${id}/complete/`,
    putaway: "/wms/admin/putaway/",
    putawayDetail: (id: string) => `/wms/admin/putaway/${id}/`,
    putawayAssign: (id: string) => `/wms/admin/putaway/${id}/assign-bin/`,
    cycleCounts: "/wms/admin/cycle-counts/",
    cycleCountRecord: (id: string) => `/wms/admin/cycle-counts/${id}/record/`,
  },
  hrm: {
    dashboard: "/hrm/admin/dashboard/",
    orgStructure: "/hrm/admin/org-structure/",
    employees: "/hrm/admin/employees/",
    employee: (id: string) => `/hrm/admin/employees/${id}/`,
    employeeDocuments: (id: string) => `/hrm/admin/employees/${id}/documents/`,
    clockIn: (id: string) => `/hrm/admin/employees/${id}/clock-in/`,
    clockOut: (id: string) => `/hrm/admin/employees/${id}/clock-out/`,
    leaveRequests: "/hrm/admin/leave-requests/",
    leaveSubmit: (id: string) => `/hrm/admin/leave-requests/${id}/submit/`,
    leaveApprove: (id: string) => `/hrm/admin/leave-requests/${id}/approve/`,
    leaveReject: (id: string) => `/hrm/admin/leave-requests/${id}/reject/`,
    assets: "/hrm/admin/assets/",
    assetAssign: (id: string) => `/hrm/admin/assets/${id}/assign/`,
    assetAssignments: "/hrm/admin/asset-assignments/",
    assetReturn: (id: string) => `/hrm/admin/asset-assignments/${id}/return/`,
  },
  payroll: {
    dashboard: "/payroll/admin/dashboard/",
    periods: "/payroll/admin/periods/",
    period: (id: string) => `/payroll/admin/periods/${id}/`,
    periodCalculate: (id: string) => `/payroll/admin/periods/${id}/calculate/`,
    periodApprove: (id: string) => `/payroll/admin/periods/${id}/approve/`,
    periodPost: (id: string) => `/payroll/admin/periods/${id}/post/`,
    periodAdjustment: (id: string) => `/payroll/admin/periods/${id}/adjustments/`,
    salaryStructures: "/payroll/admin/salary-structures/",
    payslips: "/payroll/admin/payslips/",
    payslip: (id: string) => `/payroll/admin/payslips/${id}/`,
    payslipPdf: (id: string) => `/payroll/admin/payslips/${id}/pdf/`,
    employeeHistory: (id: string) => `/payroll/admin/employees/${id}/payroll-history/`,
  },
  platform: {
    company: "/platform/company/",
    settings: "/platform/settings/",
  },
} as const;

export const API_DEFAULTS = {
  locale: "en-AU",
  currency: "AUD",
  gstRate: 0.1,
  paginationLimit: 20,
  paginationMaxLimit: 100,
  requestTimeoutMs: 30_000,
} as const;

export const STORAGE_KEYS = {
  accessToken: "a2z_access_token",
  refreshToken: "a2z_refresh_token",
  sessionKey: "a2z_session_key",
} as const;
