# Generated by Django 5.1.15 on 2026-06-21 08:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_accounting_foundation'),
        ('erp', '0009_alter_auditevent_module'),
        ('hrm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('period_number', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('pay_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('approved', 'Approved'), ('posted', 'Posted')], db_index=True, default='draft', max_length=20)),
                ('total_gross_cents', models.BigIntegerField(default=0)),
                ('total_net_cents', models.BigIntegerField(default=0)),
                ('total_deductions_cents', models.BigIntegerField(default=0)),
                ('total_super_cents', models.BigIntegerField(default=0)),
                ('total_payg_cents', models.BigIntegerField(default=0)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_periods', to=settings.AUTH_USER_MODEL)),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated_payroll_periods', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payroll_periods', to='erp.company')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_periods', to='accounting.journalentry')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_payroll_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_periods',
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('amount_cents', models.BigIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_adjustments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_adjustments', to='hrm.employee')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payroll.payrollperiod')),
            ],
            options={
                'db_table': 'payroll_adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('payslip_number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('calculated', 'Calculated'), ('finalized', 'Finalized')], default='calculated', max_length=20)),
                ('gross_cents', models.BigIntegerField(default=0)),
                ('net_cents', models.BigIntegerField(default=0)),
                ('total_allowances_cents', models.BigIntegerField(default=0)),
                ('total_deductions_cents', models.BigIntegerField(default=0)),
                ('leave_deduction_cents', models.BigIntegerField(default=0)),
                ('overtime_cents', models.BigIntegerField(default=0)),
                ('payg_withholding_cents', models.BigIntegerField(default=0)),
                ('super_cents', models.BigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payslips', to='hrm.employee')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollperiod')),
            ],
            options={
                'db_table': 'payroll_payslips',
                'ordering': ['employee__last_name', 'employee__first_name'],
            },
        ),
        migrations.CreateModel(
            name='PayslipLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('line_type', models.CharField(choices=[('earning', 'Earning'), ('allowance', 'Allowance'), ('deduction', 'Deduction'), ('leave', 'Leave Deduction'), ('overtime', 'Overtime'), ('adjustment', 'Manual Adjustment'), ('super', 'Superannuation'), ('payg', 'PAYG Withholding')], max_length=20)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('amount_cents', models.BigIntegerField()),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payslip')),
            ],
            options={
                'db_table': 'payroll_payslip_lines',
                'ordering': ['line_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('pay_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly')], default='monthly', max_length=20)),
                ('award_code', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='hrm.employee')),
            ],
            options={
                'db_table': 'payroll_salary_structures',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('component_type', models.CharField(choices=[('base', 'Base Salary'), ('allowance', 'Allowance'), ('deduction', 'Deduction'), ('super', 'Superannuation'), ('payg', 'PAYG Withholding'), ('overtime', 'Overtime')], max_length=20)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('amount_cents', models.BigIntegerField(default=0)),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_superable', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payroll.salarystructure')),
            ],
            options={
                'db_table': 'payroll_salary_components',
                'ordering': ['component_type', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['status', 'period_start'], name='idx_pay_period_status'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['employee', '-created_at'], name='idx_payslip_employee'),
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('payroll_period', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='salarycomponent',
            unique_together={('structure', 'code')},
        ),
    ]
