# Generated by Django 5.1.15 on 2026-06-20 20:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_accounting_foundation'),
        ('customers', '0001_initial'),
        ('orders', '0005_quote_workflow_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('invoice_number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_terms_days', models.PositiveIntegerField(default=30)),
                ('subtotal_ex_gst_cents', models.BigIntegerField(default=0)),
                ('gst_cents', models.BigIntegerField(default=0)),
                ('total_inc_gst_cents', models.BigIntegerField(default=0)),
                ('amount_paid_cents', models.BigIntegerField(default=0)),
                ('balance_due_cents', models.BigIntegerField(default=0)),
                ('currency_code', models.CharField(default='AUD', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoices', to='customers.customer')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_customer_invoices', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_invoices', to='accounting.journalentry')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='orders.order')),
            ],
            options={
                'db_table': 'receivables_customer_invoices',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('credit_note_number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('subtotal_ex_gst_cents', models.BigIntegerField(default=0)),
                ('gst_cents', models.BigIntegerField(default=0)),
                ('total_inc_gst_cents', models.BigIntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='credit_notes', to='customers.customer')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_credit_notes', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='accounting.journalentry')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='receivables.customerinvoice')),
            ],
            options={
                'db_table': 'receivables_credit_notes',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_ex_gst_cents', models.BigIntegerField()),
                ('line_ex_gst_cents', models.BigIntegerField()),
                ('line_gst_cents', models.BigIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='receivables.customerinvoice')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='orders.orderitem')),
            ],
            options={
                'db_table': 'receivables_customer_invoice_lines',
                'ordering': ['invoice', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('payment_number', models.CharField(max_length=30, unique=True)),
                ('payment_date', models.DateField()),
                ('amount_cents', models.BigIntegerField()),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('cash', 'Cash'), ('trade_credit', 'Trade Credit'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='customers.customer')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_payments', to='accounting.journalentry')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_customer_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'receivables_customer_payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('amount_cents', models.BigIntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payment_allocations', to='receivables.customerinvoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='receivables.customerpayment')),
            ],
            options={
                'db_table': 'receivables_payment_allocations',
            },
        ),
        migrations.AddIndex(
            model_name='customerinvoice',
            index=models.Index(fields=['status', 'due_date'], name='idx_ar_inv_status_due'),
        ),
        migrations.AddIndex(
            model_name='customerinvoice',
            index=models.Index(fields=['customer', 'status'], name='idx_ar_inv_customer'),
        ),
        migrations.AlterUniqueTogether(
            name='customerpaymentallocation',
            unique_together={('payment', 'invoice')},
        ),
    ]
