# Generated by Django 5.1.15 on 2026-06-20 20:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_product_list_performance_indexes'),
        ('inventory', '0005_inventory_stockmovement_alter_warehouse_options_and_more'),
        ('orders', '0005_quote_workflow_fields'),
        ('procurement', '0001_procurement_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseAisle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'wms_aisles',
                'ordering': ['zone__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CycleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('count_number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_counts_created', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cycle_counts', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'wms_cycle_counts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('adjustment_number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied')], default='draft', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_requests_created', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='adjustment_requests', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'wms_adjustment_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('pick_number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('assigned', 'Assigned'), ('picking', 'Picking'), ('picked', 'Picked'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pick_lists', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_lists_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_lists', to='orders.order')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pick_lists', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'wms_pick_lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PutawayTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('task_number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='putaway_tasks', to=settings.AUTH_USER_MODEL)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='putaway_tasks', to='procurement.goodsreceipt')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='putaway_tasks', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'wms_putaway_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('transfer_number', models.CharField(max_length=30, unique=True)),
                ('transfer_type', models.CharField(choices=[('warehouse', 'Warehouse to Warehouse'), ('bin', 'Bin to Bin')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('requires_approval', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers_created', to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transfers_out', to='inventory.warehouse')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transfers_in', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'wms_stock_transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sku', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_moved', models.PositiveIntegerField(default=0)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wms.stocktransfer')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transfer_lines', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'wms_stock_transfer_lines',
            },
        ),
        migrations.CreateModel(
            name='WarehouseBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('bin_type', models.CharField(choices=[('pick', 'Pick Face'), ('bulk', 'Bulk Storage'), ('staging', 'Staging'), ('receiving', 'Receiving Dock')], default='pick', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('max_units', models.PositiveIntegerField(default=0)),
                ('aisle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='wms.warehouseaisle')),
            ],
            options={
                'db_table': 'wms_bins',
                'ordering': ['aisle__zone__code', 'aisle__code', 'code'],
                'unique_together': {('aisle', 'code')},
            },
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='from_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='wms.warehousebin'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='to_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='wms.warehousebin'),
        ),
        migrations.CreateModel(
            name='PutawayTaskLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sku', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_putaway', models.PositiveIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wms.putawaytask')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='putaway_lines', to='catalog.productvariant')),
                ('target_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='putaway_lines', to='wms.warehousebin')),
            ],
            options={
                'db_table': 'wms_putaway_task_lines',
            },
        ),
        migrations.CreateModel(
            name='PickListLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sku', models.CharField(max_length=50)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('quantity_required', models.PositiveIntegerField()),
                ('quantity_picked', models.PositiveIntegerField(default=0)),
                ('pick_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wms.picklist')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pick_lines', to='catalog.productvariant')),
                ('from_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_lines', to='wms.warehousebin')),
            ],
            options={
                'db_table': 'wms_pick_list_lines',
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sku', models.CharField(max_length=50)),
                ('quantity_change', models.IntegerField()),
                ('unit_cost_cents', models.BigIntegerField(default=0)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='adjustment_lines', to='catalog.productvariant')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wms.inventoryadjustmentrequest')),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_lines', to='wms.warehousebin')),
            ],
            options={
                'db_table': 'wms_adjustment_lines',
            },
        ),
        migrations.CreateModel(
            name='CycleCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sku', models.CharField(max_length=50)),
                ('expected_qty', models.IntegerField(default=0)),
                ('counted_qty', models.IntegerField(blank=True, null=True)),
                ('cycle_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wms.cyclecount')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cycle_count_lines', to='catalog.productvariant')),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_count_lines', to='wms.warehousebin')),
            ],
            options={
                'db_table': 'wms_cycle_count_lines',
            },
        ),
        migrations.CreateModel(
            name='WarehouseZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'wms_zones',
                'ordering': ['warehouse__code', 'code'],
                'unique_together': {('warehouse', 'code')},
            },
        ),
        migrations.AddField(
            model_name='warehouseaisle',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aisles', to='wms.warehousezone'),
        ),
        migrations.CreateModel(
            name='BinInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bin_inventory', to='catalog.productvariant')),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='wms.warehousebin')),
            ],
            options={
                'db_table': 'wms_bin_inventory',
                'unique_together': {('bin', 'variant')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='warehouseaisle',
            unique_together={('zone', 'code')},
        ),
    ]
