# Generated by Django 5.1.15 on 2026-06-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='module',
            field=models.CharField(choices=[('erp', 'ERP Platform'), ('catalog', 'Catalog'), ('inventory', 'Inventory'), ('orders', 'Orders'), ('trade', 'Trade'), ('suppliers', 'Suppliers'), ('customers', 'Customers'), ('reports', 'Reports'), ('workflow', 'Workflow'), ('notifications', 'Notifications'), ('crm', 'CRM')], max_length=30),
        ),
    ]
