# Generated by Django 5.1.15 on 2026-06-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_accounting_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='module',
            field=models.CharField(choices=[('erp', 'ERP Platform'), ('catalog', 'Catalog'), ('inventory', 'Inventory'), ('orders', 'Orders'), ('trade', 'Trade'), ('suppliers', 'Suppliers'), ('customers', 'Customers'), ('reports', 'Reports'), ('workflow', 'Workflow'), ('notifications', 'Notifications'), ('crm', 'CRM'), ('quotes', 'Quotes'), ('procurement', 'Procurement'), ('wms', 'Warehouse Management'), ('accounting', 'Accounting'), ('receivables', 'Accounts Receivable'), ('payables', 'Accounts Payable')], max_length=30),
        ),
    ]
